"""
BYRD Learned Strategies

This package contains codified patterns that have been learned from experience
and converted to executable Python code by the CodeLearner.

Structure:
- desire_routing/    - Patterns for routing desires to handlers
- pattern_matching/  - Patterns for recognizing recurring situations
- decision_making/   - Patterns for making decisions in context

Each codified pattern:
- Has been used 10+ times successfully
- Has 80%+ success rate
- Is pure and deterministic (no LLM calls)
- Includes provenance in its docstring

Usage:
    from learned_strategies.desire_routing import pattern_name
    result = pattern_name(context)

The patterns in this package are auto-generated by BYRD's self-improvement
process. They represent externalized knowledge that persists beyond context
limits and executes without inference cost.
"""

__version__ = "1.0.0"
__author__ = "BYRD AGI System"
